version: '3.5'
services:
    web:
        build: 
            context: ./
            target: web-server
        volumes:
            - ./:/var/www/html
            - ./storage/app/public:/var/www/html/public/storage
            - ./storage/logs:/var/log/nginx
            - ./vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        working_dir: /var/www/html
        links:
            - app
            - mariadb
        networks:
            backend:
                ipv4_address: 192.66.5.2
    app:
        build:
            context: ./
            target: app
        volumes:
            - ./:/var/www/html
            - ./crontab:/etc/cron.d/cron
        working_dir: /var/www/html
        networks:
            backend:
                ipv4_address: 192.66.5.3

    mariadb:
        build:
            context: ./
            target: mariadb
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "3306:3306"
        volumes:
            - 'mariadb_data:/bitnami/mariadb'
        networks: 
            backend:
                ipv4_address: 192.66.5.4

volumes:
    mariadb_data:
        driver: local

networks:
    backend:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 192.66.5.1/24 